import {createContext} from 'react';

export const TeamContext = createContext([{
  idAPIfootball: "31",
  idLeague: "4424",
  idLeague2: null,
  idLeague3: null,
  idLeague4: null,
  idLeague5: null,
  idLeague6: null,
  idLeague7: null,
  idSoccerXML: null,
  idTeam: "135279",
  intFormedYear: "1883",
  intLoved: null,
  intStadiumCapacity: "41915",
  strAlternate: "SF",
  strCountry: "United States",
  strDescriptionCN: null,
  strDescriptionDE: null,
  strDescriptionEN: "The San Francisco Giants are an American professional baseball franchise based in San Francisco, California. Originally known as the New York Gothams, the team moved to San Francisco in 1958. The Giants are a member of the National League West Division of Major League Baseball (MLB) and as of October 29, 2014, the current World Series champions.\r\n\r\nAs one of the longest-established professional baseball teams, the franchise has won the most games of any team in the history of American baseball, and any North American professional sports team. The team was the first major league team based in New York City, most memorably playing at the legendary Polo Grounds. They have won 23 National League pennants and appeared in 20 World Series competitions – both records in the National League. The Giants' eight World Series Championships rank second in the National League (the St. Louis Cardinals have won 11) and are tied for fourth overall with the Boston Red Sox behind the New York Yankees with 27, the Cardinals, and the Oakland Athletics with nine. The Giants have played in the World Series 20 times (14 times in New York, 6 times in San Francisco) but boycotted the event in 1904.\r\n\r\nPlaying as the New York Giants, they won 14 pennants and 5 World Series championships behind managers such as John McGraw and Bill Terry and players like Christy Mathewson, Carl Hubbell, Mel Ott, Bobby Thomson, and Willie Mays. The Giants' franchise has the most Hall of Fame players in all of professional baseball. The Giants' rivalry with the Dodgers is one of the longest-standing and biggest rivalries in American baseball. The teams began their rivalry as the New York Giants and Brooklyn Dodgers, respectively, before both franchises moved west for the 1958 season.\r\n\r\nThe Giants have won 6 pennants and 3 World Series championships since arriving in San Francisco. The 3 championships have come in 2010, 2012 and most recently in 2014, having defeated the Kansas City Royals 4 games to 3 during the 2014 World Series.",
  strDescriptionES: null,
  strDescriptionFR: null,
  strDescriptionHU: null,
  strDescriptionIL: null,
  strDescriptionIT: null,
  strDescriptionJP: null,
  strDescriptionNL: null,
  strDescriptionNO: null,
  strDescriptionPL: null,
  strDescriptionPT: null,
  strDescriptionRU: null,
  strDescriptionSE: null,
  strDivision: null,
  strFacebook: "www.facebook.com/Giants",
  strGender: "Male",
  strInstagram: "www.instagram.com/sfgiants",
  strKeywords: "",
  strLeague: "MLB",
  strLeague2: null,
  strLeague3: null,
  strLeague4: null,
  strLeague5: null,
  strLeague6: null,
  strLeague7: null,
  strLocked: "unlocked",
  strManager: "Bruce Bochy",
  strRSS: "",
  strSport: "Baseball",
  strStadium: "AT&T Park",
  strStadiumDescription: "AT&T Park is a ballpark primarily used for hosting Major League Baseball games. It is located in the South Beach neighborhood of San Francisco, California, at 24 Willie Mays Plaza, at the corner of Third and King Streets. It has served as the home of the San Francisco Giants since 2000.\r\n\r\nOriginally named Pacific Bell Park, then SBC Park in 2003 after SBC Communications acquired Pacific Bell, the stadium was ultimately christened AT&T Park in 2006 following SBC's merger with AT&T.\r\n\r\nThe park also hosted the annual Fight Hunger Bowl, a college football bowl game from 2002 to 2013, and other occasional sporting and musical events. For the 2011 season, the park served as the home of the California Golden Bears football team while Memorial Stadium underwent seismic retrofitting and renovations.",
  strStadiumLocation: "Willie Mays Plaza San Francisco, California ",
  strStadiumThumb: "https://www.thesportsdb.com/images/media/team/stadium/srsypq1423668964.jpg",
  strTeam: "San Francisco Giants",
  strTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/mq81yb1521896622.png",
  strTeamBanner: "https://www.thesportsdb.com/images/media/team/banner/ux0rrk1552316248.jpg",
  strTeamFanart1: "https://www.thesportsdb.com/images/media/team/fanart/67vmko1552316195.jpg",
  strTeamFanart2: "https://www.thesportsdb.com/images/media/team/fanart/dmfwye1552316206.jpg",
  strTeamFanart3: "https://www.thesportsdb.com/images/media/team/fanart/wk8ax91552316220.jpg",
  strTeamFanart4: "https://www.thesportsdb.com/images/media/team/fanart/aa7c4m1552316234.jpg",
  strTeamJersey: "https://www.thesportsdb.com/images/media/team/jersey/2019-135279-Jersey.png",
  strTeamLogo: "https://www.thesportsdb.com/images/media/team/logo/rsu5pm1521896777.png",
  strTeamShort: "SF",
  strTwitter: "twitter.com/sfgiants",
  strWebsite: "www.mlb.com/giants",
  }
]);